apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 80
        path: /

