---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-ssh-keys
type: Opaque
data:
  deploy-key-shared-library: {{ b64enc (.Files.Get "secret-files/deploy-key-shared-library") }}
  ssh-agent-access-key: {{ b64enc (.Files.Get "secret-files/ssh-agent-access-key") }}
  ssh-agent-access-key.pub: {{ b64enc (.Files.Get "secret-files/ssh-agent-access-key.pub") }}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-basic-auth-credentials
type: Opaque
data:
  docker-registry-user: {{ b64enc (.Files.Get "secret-files/docker-registry-user") }}
  docker-registry-password: {{ b64enc (.Files.Get "secret-files/docker-registry-password") }}
  github-ci-user: {{ b64enc (.Files.Get "secret-files/github-ci-user") }}
  github-ci-password: {{ b64enc (.Files.Get "secret-files/github-ci-password") }}
  default-setup-user: {{ b64enc (.Files.Get "secret-files/default-setup-user") }}
  default-setup-password: {{ b64enc (.Files.Get "secret-files/default-setup-password") }}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-tokens
type: Opaque
data:
  slack-token: {{ b64enc (.Files.Get "secret-files/slack-token") }}
  github-ci-token: {{ b64enc (.Files.Get "secret-files/github-ci-token") }}
  github-oauth-client-id: {{ b64enc (.Files.Get "secret-files/github-oauth-client-id") }}
  github-oauth-client-secret: {{ b64enc (.Files.Get "secret-files/github-oauth-client-secret") }}

---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-config
type: Opaque
data:
  {{- (.Files.Glob "secret-files/terraform-config/*").AsSecrets | nindent 2 }}
